/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NewsEventsRouteImport } from './routes/news-events'
import { Route as SocialsRouteImport } from './routes/socials'
import { Route as AuthenticatedAlekaRouteImport } from './routes/_authenticated/aleka'
import { Route as DonateSuccessRouteImport } from './routes/donate.success'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as AuthenticatedAlekaIndexRouteImport } from './routes/_authenticated/aleka.index'
import { Route as AuthenticatedAlekaDonorsRouteImport } from './routes/_authenticated/aleka.donors'
import { Route as AuthenticatedAlekaEventsRouteImport } from './routes/_authenticated/aleka.events'
import { Route as AuthenticatedAlekaGalleryRouteImport } from './routes/_authenticated/aleka.gallery'
import { Route as AuthenticatedAlekaInboxRouteImport } from './routes/_authenticated/aleka.inbox'
import { Route as AuthenticatedAlekaNewsRouteImport } from './routes/_authenticated/aleka.news'
import { Route as AuthenticatedAlekaPartnersRouteImport } from './routes/_authenticated/aleka.partners'
import { Route as AuthenticatedAlekaSettingsRouteImport } from './routes/_authenticated/aleka.settings'
import { Route as AuthenticatedAlekaStaffRouteImport } from './routes/_authenticated/aleka.staff'
import { Route as AuthenticatedAlekaUsersRouteImport } from './routes/_authenticated/aleka.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEventsRoute = NewsEventsRouteImport.update({
  id: '/news-events',
  path: '/news-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialsRoute = SocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlekaRoute = AuthenticatedAlekaRouteImport.update({
  id: '/aleka',
  path: '/aleka',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DonateSuccessRoute = DonateSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DonateRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlekaIndexRoute = AuthenticatedAlekaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAlekaRoute,
} as any)
const AuthenticatedAlekaDonorsRoute =
  AuthenticatedAlekaDonorsRouteImport.update({
    id: '/donors',
    path: '/donors',
    getParentRoute: () => AuthenticatedAlekaRoute,
  } as any)
const AuthenticatedAlekaEventsRoute =
  AuthenticatedAlekaEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAlekaRoute,
  } as any)
const AuthenticatedAlekaGalleryRoute =
  AuthenticatedAlekaGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAlekaRoute,
  } as any)
const AuthenticatedAlekaInboxRoute = AuthenticatedAlekaInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAlekaRoute,
} as any)
const AuthenticatedAlekaNewsRoute = AuthenticatedAlekaNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAlekaRoute,
} as any)
const AuthenticatedAlekaPartnersRoute =
  AuthenticatedAlekaPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAlekaRoute,
  } as any)
const AuthenticatedAlekaSettingsRoute =
  AuthenticatedAlekaSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAlekaRoute,
  } as any)
const AuthenticatedAlekaStaffRoute = AuthenticatedAlekaStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAlekaRoute,
} as any)
const AuthenticatedAlekaUsersRoute = AuthenticatedAlekaUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAlekaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/news-events': typeof NewsEventsRoute
  '/socials': typeof SocialsRoute
  '/aleka': typeof AuthenticatedAlekaRouteWithChildren
  '/donate/success': typeof DonateSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/aleka/donors': typeof AuthenticatedAlekaDonorsRoute
  '/aleka/events': typeof AuthenticatedAlekaEventsRoute
  '/aleka/gallery': typeof AuthenticatedAlekaGalleryRoute
  '/aleka/inbox': typeof AuthenticatedAlekaInboxRoute
  '/aleka/news': typeof AuthenticatedAlekaNewsRoute
  '/aleka/partners': typeof AuthenticatedAlekaPartnersRoute
  '/aleka/settings': typeof AuthenticatedAlekaSettingsRoute
  '/aleka/staff': typeof AuthenticatedAlekaStaffRoute
  '/aleka/users': typeof AuthenticatedAlekaUsersRoute
  '/aleka/': typeof AuthenticatedAlekaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/news-events': typeof NewsEventsRoute
  '/socials': typeof SocialsRoute
  '/donate/success': typeof DonateSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events': typeof EventsIndexRoute
  '/news': typeof NewsIndexRoute
  '/aleka/donors': typeof AuthenticatedAlekaDonorsRoute
  '/aleka/events': typeof AuthenticatedAlekaEventsRoute
  '/aleka/gallery': typeof AuthenticatedAlekaGalleryRoute
  '/aleka/inbox': typeof AuthenticatedAlekaInboxRoute
  '/aleka/news': typeof AuthenticatedAlekaNewsRoute
  '/aleka/partners': typeof AuthenticatedAlekaPartnersRoute
  '/aleka/settings': typeof AuthenticatedAlekaSettingsRoute
  '/aleka/staff': typeof AuthenticatedAlekaStaffRoute
  '/aleka/users': typeof AuthenticatedAlekaUsersRoute
  '/aleka': typeof AuthenticatedAlekaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/news-events': typeof NewsEventsRoute
  '/socials': typeof SocialsRoute
  '/_authenticated/aleka': typeof AuthenticatedAlekaRouteWithChildren
  '/donate/success': typeof DonateSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/_authenticated/aleka/donors': typeof AuthenticatedAlekaDonorsRoute
  '/_authenticated/aleka/events': typeof AuthenticatedAlekaEventsRoute
  '/_authenticated/aleka/gallery': typeof AuthenticatedAlekaGalleryRoute
  '/_authenticated/aleka/inbox': typeof AuthenticatedAlekaInboxRoute
  '/_authenticated/aleka/news': typeof AuthenticatedAlekaNewsRoute
  '/_authenticated/aleka/partners': typeof AuthenticatedAlekaPartnersRoute
  '/_authenticated/aleka/settings': typeof AuthenticatedAlekaSettingsRoute
  '/_authenticated/aleka/staff': typeof AuthenticatedAlekaStaffRoute
  '/_authenticated/aleka/users': typeof AuthenticatedAlekaUsersRoute
  '/_authenticated/aleka/': typeof AuthenticatedAlekaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/membership'
    | '/news-events'
    | '/socials'
    | '/aleka'
    | '/donate/success'
    | '/events/$slug'
    | '/news/$slug'
    | '/events/'
    | '/news/'
    | '/aleka/donors'
    | '/aleka/events'
    | '/aleka/gallery'
    | '/aleka/inbox'
    | '/aleka/news'
    | '/aleka/partners'
    | '/aleka/settings'
    | '/aleka/staff'
    | '/aleka/users'
    | '/aleka/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/membership'
    | '/news-events'
    | '/socials'
    | '/donate/success'
    | '/events/$slug'
    | '/news/$slug'
    | '/events'
    | '/news'
    | '/aleka/donors'
    | '/aleka/events'
    | '/aleka/gallery'
    | '/aleka/inbox'
    | '/aleka/news'
    | '/aleka/partners'
    | '/aleka/settings'
    | '/aleka/staff'
    | '/aleka/users'
    | '/aleka'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/membership'
    | '/news-events'
    | '/socials'
    | '/_authenticated/aleka'
    | '/donate/success'
    | '/events/$slug'
    | '/news/$slug'
    | '/events/'
    | '/news/'
    | '/_authenticated/aleka/donors'
    | '/_authenticated/aleka/events'
    | '/_authenticated/aleka/gallery'
    | '/_authenticated/aleka/inbox'
    | '/_authenticated/aleka/news'
    | '/_authenticated/aleka/partners'
    | '/_authenticated/aleka/settings'
    | '/_authenticated/aleka/staff'
    | '/_authenticated/aleka/users'
    | '/_authenticated/aleka/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  MembershipRoute: typeof MembershipRoute
  NewsEventsRoute: typeof NewsEventsRoute
  SocialsRoute: typeof SocialsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-events': {
      id: '/news-events'
      path: '/news-events'
      fullPath: '/news-events'
      preLoaderRoute: typeof NewsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socials': {
      id: '/socials'
      path: '/socials'
      fullPath: '/socials'
      preLoaderRoute: typeof SocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aleka': {
      id: '/_authenticated/aleka'
      path: '/aleka'
      fullPath: '/aleka'
      preLoaderRoute: typeof AuthenticatedAlekaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/donate/success': {
      id: '/donate/success'
      path: '/success'
      fullPath: '/donate/success'
      preLoaderRoute: typeof DonateSuccessRouteImport
      parentRoute: typeof DonateRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aleka/': {
      id: '/_authenticated/aleka/'
      path: '/'
      fullPath: '/aleka/'
      preLoaderRoute: typeof AuthenticatedAlekaIndexRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/donors': {
      id: '/_authenticated/aleka/donors'
      path: '/donors'
      fullPath: '/aleka/donors'
      preLoaderRoute: typeof AuthenticatedAlekaDonorsRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/events': {
      id: '/_authenticated/aleka/events'
      path: '/events'
      fullPath: '/aleka/events'
      preLoaderRoute: typeof AuthenticatedAlekaEventsRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/gallery': {
      id: '/_authenticated/aleka/gallery'
      path: '/gallery'
      fullPath: '/aleka/gallery'
      preLoaderRoute: typeof AuthenticatedAlekaGalleryRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/inbox': {
      id: '/_authenticated/aleka/inbox'
      path: '/inbox'
      fullPath: '/aleka/inbox'
      preLoaderRoute: typeof AuthenticatedAlekaInboxRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/news': {
      id: '/_authenticated/aleka/news'
      path: '/news'
      fullPath: '/aleka/news'
      preLoaderRoute: typeof AuthenticatedAlekaNewsRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/partners': {
      id: '/_authenticated/aleka/partners'
      path: '/partners'
      fullPath: '/aleka/partners'
      preLoaderRoute: typeof AuthenticatedAlekaPartnersRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/settings': {
      id: '/_authenticated/aleka/settings'
      path: '/settings'
      fullPath: '/aleka/settings'
      preLoaderRoute: typeof AuthenticatedAlekaSettingsRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/staff': {
      id: '/_authenticated/aleka/staff'
      path: '/staff'
      fullPath: '/aleka/staff'
      preLoaderRoute: typeof AuthenticatedAlekaStaffRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
    '/_authenticated/aleka/users': {
      id: '/_authenticated/aleka/users'
      path: '/users'
      fullPath: '/aleka/users'
      preLoaderRoute: typeof AuthenticatedAlekaUsersRouteImport
      parentRoute: typeof AuthenticatedAlekaRoute
    }
  }
}

interface AuthenticatedAlekaRouteChildren {
  AuthenticatedAlekaDonorsRoute: typeof AuthenticatedAlekaDonorsRoute
  AuthenticatedAlekaEventsRoute: typeof AuthenticatedAlekaEventsRoute
  AuthenticatedAlekaGalleryRoute: typeof AuthenticatedAlekaGalleryRoute
  AuthenticatedAlekaInboxRoute: typeof AuthenticatedAlekaInboxRoute
  AuthenticatedAlekaNewsRoute: typeof AuthenticatedAlekaNewsRoute
  AuthenticatedAlekaPartnersRoute: typeof AuthenticatedAlekaPartnersRoute
  AuthenticatedAlekaSettingsRoute: typeof AuthenticatedAlekaSettingsRoute
  AuthenticatedAlekaStaffRoute: typeof AuthenticatedAlekaStaffRoute
  AuthenticatedAlekaUsersRoute: typeof AuthenticatedAlekaUsersRoute
  AuthenticatedAlekaIndexRoute: typeof AuthenticatedAlekaIndexRoute
}

const AuthenticatedAlekaRouteChildren: AuthenticatedAlekaRouteChildren = {
  AuthenticatedAlekaDonorsRoute: AuthenticatedAlekaDonorsRoute,
  AuthenticatedAlekaEventsRoute: AuthenticatedAlekaEventsRoute,
  AuthenticatedAlekaGalleryRoute: AuthenticatedAlekaGalleryRoute,
  AuthenticatedAlekaInboxRoute: AuthenticatedAlekaInboxRoute,
  AuthenticatedAlekaNewsRoute: AuthenticatedAlekaNewsRoute,
  AuthenticatedAlekaPartnersRoute: AuthenticatedAlekaPartnersRoute,
  AuthenticatedAlekaSettingsRoute: AuthenticatedAlekaSettingsRoute,
  AuthenticatedAlekaStaffRoute: AuthenticatedAlekaStaffRoute,
  AuthenticatedAlekaUsersRoute: AuthenticatedAlekaUsersRoute,
  AuthenticatedAlekaIndexRoute: AuthenticatedAlekaIndexRoute,
}

const AuthenticatedAlekaRouteWithChildren =
  AuthenticatedAlekaRoute._addFileChildren(AuthenticatedAlekaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlekaRoute: typeof AuthenticatedAlekaRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlekaRoute: AuthenticatedAlekaRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DonateRouteChildren {
  DonateSuccessRoute: typeof DonateSuccessRoute
}

const DonateRouteChildren: DonateRouteChildren = {
  DonateSuccessRoute: DonateSuccessRoute,
}

const DonateRouteWithChildren =
  DonateRoute._addFileChildren(DonateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRouteWithChildren,
  GalleryRoute: GalleryRoute,
  MembershipRoute: MembershipRoute,
  NewsEventsRoute: NewsEventsRoute,
  SocialsRoute: SocialsRoute,
  EventsSlugRoute: EventsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
